version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: null
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app-tpfoyer:
    depends_on:
      - mysqldb
    image: liwaayari/tp-foyer:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: null,
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8089

    stdin_open: true
    tty: true

volumes:
  db-data: