version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""  # Leave empty as per your config
      MYSQL_DATABASE: db       # Matches your spring.datasource.url
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app-tpfoyer:
    depends_on:
      - mysqldb
    image: liwaayari/tp-foyer:latest  # Replace with your Docker Hub repo
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /tpfoyer
    stdin_open: true
    tty: true

volumes:
  db-data: